import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateInput,cleanNickname,makeToken,hashToken,roundWinner,stopwatchXp,SERVER_RULES} from '../editions/hisaab/server/core.mjs';

test('guest tokens contain256bits and persist only SHA256 at DB boundary',async()=>{const a=makeToken(),b=makeToken();assert.match(a,/^[a-f0-9]{64}$/);assert.notEqual(a,b);const hash=await hashToken(a);assert.match(hash,/^[a-f0-9]{64}$/);assert.notEqual(hash,a);assert.equal(await hashToken(a),hash);await assert.rejects(hashToken(''),{code:'UNAUTHORIZED'});});
test('input never accepts client claimed score, timing, identity, keys',()=>{const x=validateInput({action:'answer',roomId:crypto.randomUUID(),round:1,choice:0,requestId:crypto.randomUUID(),elapsedMs:1,score:999,xp:999,correct:true,correctIndex:0,sessionId:'other',playerId:'other',tokenHash:'x',serverNow:0});for(const key of ['elapsedMs','score','xp','correct','correctIndex','sessionId','playerId','tokenHash','serverNow'])assert.equal(key in x.payload,false);});
test('input rejects invalid choice, round, room, request ID and actions',()=>{for(const extra of [{choice:4},{choice:-1},{choice:0.5},{round:0},{round:6},{roomId:'no'},{requestId:'no'}])assert.throws(()=>validateInput({action:'answer',roomId:crypto.randomUUID(),round:1,choice:0,requestId:crypto.randomUUID(),...extra}));assert.throws(()=>validateInput({action:'admin'}));assert.throws(()=>validateInput({action:'answer'}));});
test('nicknames strip controls, have bounded Unicode length',()=>{assert.equal(cleanNickname('  भा\u200bई   साहब '),'भाई साहब');assert.throws(()=>cleanNickname('x'));assert.throws(()=>cleanNickname('🙂'.repeat(25)));assert.equal(cleanNickname('🙂'.repeat(24)),'🙂'.repeat(24));});
test('timing ties include120ms and correct answer precedes speed',()=>{const a={playerId:'a',correct:true,elapsedMs:1000},b={playerId:'b',correct:true,elapsedMs:1120};assert.equal(roundWinner([a,b]),null);assert.equal(roundWinner([a,{...b,elapsedMs:1121}]),'a');assert.equal(roundWinner([{...a,correct:false},{...b,elapsedMs:15000}]),'b');assert.equal(roundWinner([{...a,correct:false},{...b,correct:false}]),null);});
test('stopwatch tier boundaries are strict and wrong answers earnzero',()=>{assert.deepEqual([7999,8000,14999,15000,30000].map(ms=>stopwatchXp(true,ms)),[30,20,20,10,10]);assert.equal(stopwatchXp(false,1),0);assert.equal(SERVER_RULES.rounds,5);});
test('Edge deployed validator exactly matches testedvalidator',()=>{assert.equal(fs.readFileSync(new URL('../editions/hisaab/server/core.mjs',import.meta.url),'utf8'),fs.readFileSync(new URL('../supabase/hisaab/functions/hisaab-game/core.mjs',import.meta.url),'utf8'));});
test('SQL schema exposure and security boundary stay explicit',()=>{const sql=fs.readFileSync(new URL('../supabase/hisaab/schema.sql',import.meta.url),'utf8');assert.match(sql,/revoke all on function public\.hisaab_game\(text,text,jsonb,text\) from public, anon, authenticated/);assert.match(sql,/language plpgsql security invoker set search_path=''/);assert.match(sql,/enable row level security/);assert.match(sql,/primary key\(room_id,round,session_id\)/);assert.match(sql,/issued_at/);assert.match(sql,/p_action='deleteSession'/);});
